apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artemis.fullname" . }}-configure-master
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
data:

  template-master.xml: |
    <configuration xmlns="urn:activemq" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">
      <core xmlns="urn:activemq:core" xsi:schemaLocation="urn:activemq:core ">

        <ha-policy>
          <replication>
            <master>
              <group-name>to-be-set-by-configure-cluster.sh</group-name>
              <!--we need this for auto failback-->
              <check-for-live-server>false</check-for-live-server>
            </master>
          </replication>
        </ha-policy>
      </core>
    </configuration>

  anycast-queue.xml: |
    <configuration xmlns="urn:activemq" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">
      <core xmlns="urn:activemq:core" xsi:schemaLocation="urn:activemq:core ">
        <addresses>
    {{- range $i, $a := .Values.anycast }}
          <address name="{{ $a }}">
            <anycast>
              <queue name="{{ $a }}"/>
            </anycast>
          </address>
    {{- end }}
        </addresses>
      </core>
    </configuration>

  multicast-queue.xml: |
    <configuration xmlns="urn:activemq" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">
      <core xmlns="urn:activemq:core" xsi:schemaLocation="urn:activemq:core ">
        <addresses>
    {{-  range $i, $a := .Values.multicast  }}
          <address name="{{ $a }}">
            <multicast>
              <queue name="{{ $a }}"/>
            </multicast>
          </address>
    {{- end }}
        </addresses>
      </core>
    </configuration>

  configure-cluster.sh: |
    
    {{ $name := default .Chart.Name .Values.nameOverride }}
    {{ $releaseName := printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}

    set -e
    echo Copying common configuration
    cp /opt/configure-common/template-common.xml /var/lib/artemis/etc-override/broker-10.xml

    echo Assigning node as master
    cp /opt/configure-master/template-master.xml /var/lib/artemis/etc-override/broker-11.xml

    echo Assigning queues
    cp /opt/configure-master/anycast-queue.xml /var/lib/artemis/etc-override/broker-12.xml
    cp /opt/configure-master/multicast-queue.xml /var/lib/artemis/etc-override/broker-13.xml

    GROUPNAME=$(echo ${HOSTNAME} | sed -re 's/(-slave|-master)//')
    echo Setting the group-name for slave to ${GROUPNAME}
    xmlstarlet ed -L \
    -N activemq="urn:activemq" \
    -N core="urn:activemq:core" \
    -u "/activemq:configuration/core:core/core:ha-policy/core:replication/core:master/core:group-name" \
    -v "${GROUPNAME}" /var/lib/artemis/etc-override/broker-11.xml

    echo Setting the connector-ref to ${HOSTNAME}
          xmlstarlet ed -L \
            -N activemq="urn:activemq" \
            -N core="urn:activemq:core" \
            -u "/activemq:configuration/core:core/core:cluster-connections/core:cluster-connection[@name='{{ $releaseName }}']/core:connector-ref" \
            -v "${HOSTNAME}" /var/lib/artemis/etc-override/broker-10.xml

